[package]
name = "dake"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
bincode = "1.3.3"
derive-getters = "0.5.0"
log = "0.4.28"
serde = { version = "1.0.139", features = ["derive"] }
tempfile = "3.22.0"
simple_logger = "5"
tokio = { version= "1.47.1", features = ["full"] }

