FROM rust:1.83-alpine AS builder

RUN apk add --no-cache musl-dev openssl-dev pkgconfig

RUN rustup toolchain install nightly && rustup default nightly

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
 
RUN mkdir src && echo "fn main() {}" > src/main.rs

RUN cargo +nightly build || true

COPY . .

RUN cargo +nightly build

FROM alpine:latest
RUN apk add --no-cache make build-base
COPY --from=builder /app/target/debug/dake /usr/local/bin/dake

ENTRYPOINT ["/bin/sh", "-c", "sleep infinity"]
